/**
 * Character tables used by the transliterator.
 *
 * Kept separate from the algorithm so a locale pack can be swapped or extended
 * without touching the pipeline.
 */

/* ------------------------------- Devanagari ------------------------------- */

export const DEVANAGARI_INDEPENDENT_VOWELS: Record<string, string> = {
  अ: 'a',
  आ: 'a',
  इ: 'i',
  ई: 'i',
  उ: 'u',
  ऊ: 'u',
  ऋ: 'ri',
  ॠ: 'ri',
  ऌ: 'li',
  ऍ: 'e',
  ऎ: 'e',
  ए: 'e',
  ऐ: 'ai',
  ऑ: 'o',
  ऒ: 'o',
  ओ: 'o',
  औ: 'au',
};

export const DEVANAGARI_MATRAS: Record<string, string> = {
  'ा': 'a',
  'ि': 'i',
  'ी': 'i',
  'ु': 'u',
  'ू': 'u',
  'ृ': 'ri',
  'ॄ': 'ri',
  'ॅ': 'e',
  'ॆ': 'e',
  'े': 'e',
  'ै': 'ai',
  'ॉ': 'o',
  'ॊ': 'o',
  'ो': 'o',
  'ौ': 'au',
};

export const DEVANAGARI_CONSONANTS: Record<string, string> = {
  क: 'k',
  ख: 'kh',
  ग: 'g',
  घ: 'gh',
  ङ: 'n',
  च: 'ch',
  छ: 'chh',
  ज: 'j',
  झ: 'jh',
  ञ: 'n',
  ट: 't',
  ठ: 'th',
  ड: 'd',
  ढ: 'dh',
  ण: 'n',
  त: 't',
  थ: 'th',
  द: 'd',
  ध: 'dh',
  न: 'n',
  ऩ: 'n',
  प: 'p',
  फ: 'ph',
  ब: 'b',
  भ: 'bh',
  म: 'm',
  य: 'y',
  र: 'r',
  ऱ: 'r',
  ल: 'l',
  ळ: 'l',
  ऴ: 'l',
  व: 'v',
  श: 'sh',
  ष: 'sh',
  स: 's',
  ह: 'h',
  क़: 'q',
  ख़: 'kh',
  ग़: 'gh',
  ज़: 'z',
  ड़: 'r',
  ढ़: 'rh',
  फ़: 'f',
  य़: 'y',
};

export const DEVANAGARI_VIRAMA = '्';
export const DEVANAGARI_NUKTA = '़';

export const DEVANAGARI_SIGNS: Record<string, string> = {
  'ं': 'n',
  'ँ': 'n',
  'ः': 'h',
  '़': '',
  'ऽ': '',
  '्': '',
};

/** Base letters that combine with the nukta sign into a distinct phoneme. */
export const DEVANAGARI_NUKTA_PAIRS: Record<string, string> = {
  क: 'क़',
  ख: 'ख़',
  ग: 'ग़',
  ज: 'ज़',
  ड: 'ड़',
  ढ: 'ढ़',
  फ: 'फ़',
  य: 'य़',
  न: 'ऩ',
  र: 'ऱ',
};

/* --------------------------------- Arabic --------------------------------- */

export const ARABIC_CONSONANTS: Record<string, string> = {
  'ب': 'b',
  'ت': 't',
  'ث': 'th',
  'ج': 'j',
  'ح': 'h',
  'خ': 'kh',
  'د': 'd',
  'ذ': 'dh',
  'ر': 'r',
  'ز': 'z',
  'س': 's',
  'ش': 'sh',
  'ص': 's',
  'ض': 'd',
  'ط': 't',
  'ظ': 'z',
  'ع': 'a',
  'غ': 'gh',
  'ف': 'f',
  'ق': 'q',
  'ك': 'k',
  'ک': 'k',
  'ل': 'l',
  'م': 'm',
  'ن': 'n',
  'ه': 'h',
  'ہ': 'h',
  'پ': 'p',
  'چ': 'ch',
  'ژ': 'zh',
  'گ': 'g',
  'ٹ': 't',
  'ڈ': 'd',
  'ڑ': 'r',
  'ں': 'n',
  'ھ': 'h',
};

export const ARABIC_VOWELS: Record<string, string> = {
  'ا': 'a',
  'أ': 'a',
  'إ': 'i',
  'آ': 'a',
  'ٱ': 'a',
  'ة': 'a',
  'ى': 'a',
  'ے': 'e',
  'ي': 'i',
  'ی': 'i',
  'و': 'u',
  'ؤ': 'u',
  'ئ': 'i',
  'ء': '',
};

export const ARABIC_DIACRITICS: Record<string, string> = {
  'َ': 'a',
  'ُ': 'u',
  'ِ': 'i',
  'ً': 'an',
  'ٌ': 'un',
  'ٍ': 'in',
  'ْ': '',
  'ّ': '',
  'ٰ': 'a',
  'ٓ': '',
  'ٔ': '',
  'ٕ': '',
};

/* -------------------------------- Cyrillic -------------------------------- */

export const CYRILLIC_MAP: Record<string, string> = {
  а: 'a',
  б: 'b',
  в: 'v',
  г: 'g',
  ґ: 'g',
  д: 'd',
  е: 'e',
  ё: 'yo',
  є: 'ye',
  ж: 'zh',
  з: 'z',
  и: 'i',
  і: 'i',
  ї: 'yi',
  й: 'y',
  ј: 'j',
  к: 'k',
  л: 'l',
  љ: 'lj',
  м: 'm',
  н: 'n',
  њ: 'nj',
  о: 'o',
  п: 'p',
  р: 'r',
  с: 's',
  т: 't',
  ћ: 'c',
  у: 'u',
  ў: 'u',
  ф: 'f',
  х: 'kh',
  ц: 'ts',
  ч: 'ch',
  џ: 'dz',
  ш: 'sh',
  щ: 'shch',
  ъ: '',
  ы: 'y',
  ь: '',
  э: 'e',
  ю: 'yu',
  я: 'ya',
};

/* ---------------------------------- Greek --------------------------------- */

export const GREEK_DIGRAPHS: Record<string, string> = {
  // `ou` rather than the phonetic `u`: Papadopoulos is how the name is written.
  ου: 'ou',
  ευ: 'ev',
  αυ: 'av',
  ει: 'i',
  οι: 'i',
  αι: 'e',
  υι: 'i',
  μπ: 'b',
  ντ: 'd',
  γκ: 'g',
  γγ: 'ng',
  τζ: 'tz',
  τσ: 'ts',
};

export const GREEK_MAP: Record<string, string> = {
  α: 'a',
  β: 'v',
  γ: 'g',
  δ: 'd',
  ε: 'e',
  ζ: 'z',
  η: 'i',
  θ: 'th',
  ι: 'i',
  κ: 'k',
  λ: 'l',
  μ: 'm',
  ν: 'n',
  ξ: 'x',
  ο: 'o',
  π: 'p',
  ρ: 'r',
  σ: 's',
  ς: 's',
  τ: 't',
  υ: 'y',
  φ: 'f',
  χ: 'ch',
  ψ: 'ps',
  ω: 'o',
};

/* --------------------------------- Hebrew --------------------------------- */

export const HEBREW_MAP: Record<string, string> = {
  'א': 'a',
  'ב': 'b',
  'ג': 'g',
  'ד': 'd',
  'ה': 'h',
  'ו': 'v',
  'ז': 'z',
  'ח': 'ch',
  'ט': 't',
  'י': 'y',
  'כ': 'k',
  'ך': 'k',
  'ל': 'l',
  'מ': 'm',
  'ם': 'm',
  'נ': 'n',
  'ן': 'n',
  'ס': 's',
  'ע': 'a',
  'פ': 'p',
  'ף': 'f',
  'צ': 'ts',
  'ץ': 'ts',
  'ק': 'k',
  'ר': 'r',
  'ש': 'sh',
  'ת': 't',
};

/* ----------------------------------- Han ---------------------------------- */

/**
 * Pinyin for the most frequent Chinese family names. Han support is
 * deliberately surname-level: full given-name transliteration needs a
 * dictionary far larger than this package should carry.
 */
export const HAN_SURNAMES: Record<string, string> = {
  王: 'wang',
  李: 'li',
  张: 'zhang',
  張: 'zhang',
  刘: 'liu',
  劉: 'liu',
  陈: 'chen',
  陳: 'chen',
  杨: 'yang',
  楊: 'yang',
  黄: 'huang',
  黃: 'huang',
  赵: 'zhao',
  趙: 'zhao',
  吴: 'wu',
  吳: 'wu',
  周: 'zhou',
  徐: 'xu',
  孙: 'sun',
  孫: 'sun',
  马: 'ma',
  馬: 'ma',
  朱: 'zhu',
  胡: 'hu',
  郭: 'guo',
  何: 'he',
  高: 'gao',
  林: 'lin',
  罗: 'luo',
  羅: 'luo',
  郑: 'zheng',
  鄭: 'zheng',
  梁: 'liang',
  谢: 'xie',
  謝: 'xie',
  宋: 'song',
  唐: 'tang',
  许: 'xu',
  許: 'xu',
  邓: 'deng',
  鄧: 'deng',
  韩: 'han',
  韓: 'han',
  冯: 'feng',
  馮: 'feng',
  曹: 'cao',
  彭: 'peng',
  曾: 'zeng',
  萧: 'xiao',
  蕭: 'xiao',
  田: 'tian',
  董: 'dong',
  袁: 'yuan',
  潘: 'pan',
  于: 'yu',
  蒋: 'jiang',
  蔣: 'jiang',
  蔡: 'cai',
  余: 'yu',
  杜: 'du',
  叶: 'ye',
  葉: 'ye',
  程: 'cheng',
  苏: 'su',
  蘇: 'su',
  魏: 'wei',
  吕: 'lu',
  呂: 'lu',
  丁: 'ding',
  任: 'ren',
  沈: 'shen',
  姚: 'yao',
  卢: 'lu',
  盧: 'lu',
  姜: 'jiang',
  崔: 'cui',
  钟: 'zhong',
  鐘: 'zhong',
  谭: 'tan',
  譚: 'tan',
  陆: 'lu',
  陸: 'lu',
  汪: 'wang',
  范: 'fan',
  金: 'jin',
  石: 'shi',
  廖: 'liao',
  贾: 'jia',
  賈: 'jia',
  夏: 'xia',
  韦: 'wei',
  韋: 'wei',
  付: 'fu',
  方: 'fang',
  白: 'bai',
  邹: 'zou',
  鄒: 'zou',
  孟: 'meng',
  熊: 'xiong',
  秦: 'qin',
  邱: 'qiu',
  江: 'jiang',
  尹: 'yin',
  薛: 'xue',
  闫: 'yan',
  段: 'duan',
  雷: 'lei',
  侯: 'hou',
  龙: 'long',
  龍: 'long',
  史: 'shi',
  陶: 'tao',
  黎: 'li',
  贺: 'he',
  賀: 'he',
  顾: 'gu',
  顧: 'gu',
  毛: 'mao',
  郝: 'hao',
  龚: 'gong',
  龔: 'gong',
  邵: 'shao',
  万: 'wan',
  萬: 'wan',
  钱: 'qian',
  錢: 'qian',
  严: 'yan',
  嚴: 'yan',
  覃: 'qin',
  武: 'wu',
  戴: 'dai',
  莫: 'mo',
  孔: 'kong',
  向: 'xiang',
  常: 'chang',
};


/**
 * Pinyin for characters common in Chinese *given* names.
 *
 * Together with {@link HAN_SURNAMES} this covers the majority of two- and
 * three-character names. Han support remains table-driven rather than general:
 * a complete mapping needs a dictionary far larger than this package carries.
 */
export const HAN_GIVEN: Record<string, string> = {
  伟: 'wei', 偉: 'wei', 明: 'ming', 军: 'jun', 軍: 'jun', 强: 'qiang', 強: 'qiang',
  磊: 'lei', 洋: 'yang', 勇: 'yong', 艳: 'yan', 豔: 'yan', 杰: 'jie', 傑: 'jie',
  娟: 'juan', 涛: 'tao', 濤: 'tao', 超: 'chao', 秀: 'xiu', 英: 'ying', 霞: 'xia',
  平: 'ping', 刚: 'gang', 剛: 'gang', 桂: 'gui', 芳: 'fang', 娜: 'na', 敏: 'min',
  静: 'jing', 靜: 'jing', 丽: 'li', 麗: 'li', 玲: 'ling', 华: 'hua', 華: 'hua',
  建: 'jian', 国: 'guo', 國: 'guo', 文: 'wen', 志: 'zhi', 海: 'hai', 峰: 'feng',
  波: 'bo', 辉: 'hui', 輝: 'hui', 鹏: 'peng', 鵬: 'peng', 龙: 'long', 龍: 'long',
  飞: 'fei', 飛: 'fei', 斌: 'bin', 宇: 'yu', 浩: 'hao', 鑫: 'xin', 佳: 'jia',
  欣: 'xin', 婷: 'ting', 雪: 'xue', 梅: 'mei', 兰: 'lan', 蘭: 'lan', 燕: 'yan',
  红: 'hong', 紅: 'hong', 春: 'chun', 秋: 'qiu', 冬: 'dong', 心: 'xin', 爱: 'ai',
  愛: 'ai', 小: 'xiao', 大: 'da', 天: 'tian', 子: 'zi', 民: 'min', 新: 'xin',
  成: 'cheng', 立: 'li', 中: 'zhong', 正: 'zheng', 安: 'an', 康: 'kang',
  健: 'jian', 生: 'sheng', 家: 'jia', 俊: 'jun', 凯: 'kai', 凱: 'kai',
  琳: 'lin', 婉: 'wan', 慧: 'hui', 珍: 'zhen', 玉: 'yu', 兵: 'bing', 亮: 'liang',
  磬: 'qing', 清: 'qing', 青: 'qing', 志强: 'zhiqiang', 秀英: 'xiuying',
};

/* ------------------------- Curated name equivalences ----------------------- */

/**
 * High-frequency native-script name forms whose conventional romanisation is
 * not recoverable by rule (Arabic script omits short vowels, so `محمد` can only
 * be spelled `mhmd` mechanically).
 */
export const CURATED_TRANSLITERATIONS: Record<string, string> = {
  // Arabic / Persian / Urdu
  'محمد': 'muhammad',
  'محمّد': 'muhammad',
  'مُحَمَّد': 'muhammad',
  'أحمد': 'ahmad',
  'احمد': 'ahmad',
  'محمود': 'mahmoud',
  'علي': 'ali',
  'على': 'ali',
  'عمر': 'omar',
  'عثمان': 'usman',
  'حسن': 'hassan',
  'حسين': 'hussain',
  'خالد': 'khalid',
  'عبد': 'abdul',
  'عبدالله': 'abdullah',
  'عبد الله': 'abdullah',
  'عبدالرحمن': 'abdulrahman',
  'الرحمن': 'rahman',
  'رحمن': 'rahman',
  'رحمان': 'rahman',
  'ابراهيم': 'ibrahim',
  'إبراهيم': 'ibrahim',
  'اسماعيل': 'ismail',
  'يوسف': 'yusuf',
  'يعقوب': 'yaqub',
  'موسى': 'musa',
  'عيسى': 'isa',
  'زينب': 'zainab',
  'فاطمة': 'fatima',
  'عائشة': 'aisha',
  'خديجة': 'khadija',
  'مريم': 'maryam',
  'سارة': 'sara',
  'نور': 'noor',
  'ليلى': 'laila',
  'سلمى': 'salma',
  'هدى': 'huda',
  'أمينة': 'amina',
  'رشيد': 'rashid',
  'كريم': 'karim',
  'سعيد': 'saeed',
  'سعد': 'saad',
  'ناصر': 'nasser',
  'طارق': 'tariq',
  'جمال': 'jamal',
  'كمال': 'kamal',
  'سليم': 'salim',
  'سليمان': 'sulaiman',
  'داود': 'dawood',
  'ياسر': 'yasser',
  'زياد': 'ziad',
  'وليد': 'walid',
  'ماجد': 'majid',
  'راشد': 'rashid',
  'صالح': 'saleh',
  'عادل': 'adel',
  'أمير': 'amir',
  'امير': 'amir',
  'بلال': 'bilal',
  'حمزة': 'hamza',
  'إلياس': 'ilyas',
  'انور': 'anwar',
  'أنور': 'anwar',
  'اسلام': 'islam',
  'شريف': 'sharif',
  'فيصل': 'faisal',
  'غالب': 'ghalib',
  'نبيل': 'nabil',
  'هاني': 'hani',
  'وسيم': 'wasim',
  'يحيى': 'yahya',
  'زكريا': 'zakaria',
  'الدين': 'uddin',
  'دين': 'din',
  'خان': 'khan',
  'شاه': 'shah',
  'ملك': 'malik',
  'حق': 'haq',
  'اقبال': 'iqbal',
  'اختر': 'akhtar',
  'اسلم': 'aslam',
  'رضا': 'raza',
  'جان': 'jan',

  // Hebrew
  'שרה': 'sara',
  'רחל': 'rachel',
  'לאה': 'leah',
  'מרים': 'miriam',
  'אסתר': 'esther',
  'חנה': 'hannah',
  'מיכל': 'michal',
  'נועה': 'noa',
  'יעל': 'yael',
  'תמר': 'tamar',
  'דוד': 'david',
  'משה': 'moshe',
  'יעקב': 'yaakov',
  'אברהם': 'avraham',
  'יצחק': 'yitzhak',
  'יוסף': 'yosef',
  'שמואל': 'shmuel',
  'אורי': 'uri',
  'איתן': 'eitan',
  'נועם': 'noam',
  'עמית': 'amit',
  'ישראל': 'israel',
  'כהן': 'cohen',
  'לוי': 'levi',
  'כץ': 'katz',
  'פרץ': 'peretz',
  'מזרחי': 'mizrahi',
  'אזולאי': 'azoulay',
  'ביטון': 'biton',
  'דהן': 'dahan',
  'גבאי': 'gabay',
  'שפירא': 'shapira',
  'פרידמן': 'friedman',
  'רוזנברג': 'rosenberg',
  'גולדברג': 'goldberg',

  // Devanagari
  'राहुल': 'rahul',
  'शर्मा': 'sharma',
  'कुमार': 'kumar',
  'सिंह': 'singh',
  'गुप्ता': 'gupta',
  'वर्मा': 'verma',
  'यादव': 'yadav',
  'पटेल': 'patel',
  'रेड्डी': 'reddy',
  'नायर': 'nair',
  'मेहता': 'mehta',
  'शाह': 'shah',
  'जैन': 'jain',
  'अग्रवाल': 'agarwal',
  'चौधरी': 'chaudhary',
  'मिश्रा': 'mishra',
  'पांडे': 'pandey',
  'पाण्डेय': 'pandey',
  'तिवारी': 'tiwari',
  'दुबे': 'dubey',
  'त्रिपाठी': 'tripathi',
  'श्रीवास्तव': 'srivastava',
  'चटर्जी': 'chatterjee',
  'बनर्जी': 'banerjee',
  'मुखर्जी': 'mukherjee',
  'घोष': 'ghosh',
  'बोस': 'bose',
  'दास': 'das',
  'राय': 'rai',
  'रॉय': 'roy',
  'सेन': 'sen',
  'देसाई': 'desai',
  'जोशी': 'joshi',
  'कुलकर्णी': 'kulkarni',
  'देशपांडे': 'deshpande',
  'पाटिल': 'patil',
  'शिंदे': 'shinde',
  'गायकवाड़': 'gaikwad',
  'अजय': 'ajay',
  'विजय': 'vijay',
  'संजय': 'sanjay',
  'अमित': 'amit',
  'सुनील': 'sunil',
  'अनिल': 'anil',
  'रवि': 'ravi',
  'रमेश': 'ramesh',
  'सुरेश': 'suresh',
  'महेश': 'mahesh',
  'दिनेश': 'dinesh',
  'राजेश': 'rajesh',
  'मुकेश': 'mukesh',
  'नरेश': 'naresh',
  'प्रकाश': 'prakash',
  'विकास': 'vikas',
  'दीपक': 'deepak',
  'मनोज': 'manoj',
  'संदीप': 'sandeep',
  'प्रदीप': 'pradeep',
  'अरुण': 'arun',
  'वरुण': 'varun',
  'करण': 'karan',
  'रोहित': 'rohit',
  'मोहित': 'mohit',
  'अंकित': 'ankit',
  'सचिन': 'sachin',
  'नितिन': 'nitin',
  'गौरव': 'gaurav',
  'सौरव': 'saurav',
  'अभिषेक': 'abhishek',
  'आकाश': 'akash',
  'विवेक': 'vivek',
  'अनुज': 'anuj',
  'नेहा': 'neha',
  'पूजा': 'pooja',
  'प्रिया': 'priya',
  'अंजलि': 'anjali',
  'काजल': 'kajal',
  'दिव्या': 'divya',
  'श्वेता': 'shweta',
  'सुनीता': 'sunita',
  'अनीता': 'anita',
  'कविता': 'kavita',
  'रेखा': 'rekha',
  'सीमा': 'seema',
  'मीना': 'meena',
  'गीता': 'geeta',
  'राधा': 'radha',
  'सीता': 'sita',
  'लक्ष्मी': 'lakshmi',
  'सरस्वती': 'saraswati',
  'पार्वती': 'parvati',
  'राम': 'ram',
  'श्याम': 'shyam',
  'कृष्ण': 'krishna',
  'गणेश': 'ganesh',
  'शिव': 'shiv',
  'हरि': 'hari',
  'गोपाल': 'gopal',
  'मोहन': 'mohan',
  'सोहन': 'sohan',
  'रोहन': 'rohan',
  'अर्जुन': 'arjun',
  'आदित्य': 'aditya',
  'सिद्धार्थ': 'siddharth',
  'ऋषभ': 'rishabh',
  'हर्ष': 'harsh',
  'यश': 'yash',
  'देव': 'dev',
  'अमन': 'aman',
  'नमन': 'naman',
  'सागर': 'sagar',
  'सत्येंद्र': 'satyendra',
  'नरेंद्र': 'narendra',
  'राजेंद्र': 'rajendra',
  'महेंद्र': 'mahendra',
  'सुरेंद्र': 'surendra',
  'देवेंद्र': 'devendra',
  'जितेंद्र': 'jitendra',
  'वीरेंद्र': 'virendra',
};
