import type { AliasGroup } from './types.js';

/**
 * Built-in alias tables.
 *
 * Split by evidence strength on purpose:
 *  - `variant`         : same name, different orthography. Near-certain.
 *  - `transliteration` : same source name romanised differently. Near-certain.
 *  - `nickname`        : diminutive / short form. Strong but not certain.
 *  - `translation`     : cross-language cognate. Weak; off by default in strict mode.
 */

/** Same name, different spelling. */
const SPELLING_VARIANTS: string[][] = [
  ['catherine', 'katherine', 'kathryn', 'katharine', 'cathryn', 'katheryn'],
  ['stephen', 'steven', 'stefan', 'stephan'],
  ['geoffrey', 'jeffrey', 'jeffery', 'geoffery'],
  ['sara', 'sarah', 'sera'],
  ['sofia', 'sophia', 'sophie', 'sofie'],
  ['ann', 'anne', 'anna'],
  ['aaron', 'aron', 'arron'],
  ['brian', 'bryan', 'brien'],
  ['carl', 'karl'],
  ['claire', 'clare'],
  ['deborah', 'debra', 'debbra'],
  ['dennis', 'denis'],
  ['eric', 'erik', 'erick'],
  ['jon', 'john', 'johnn'],
  ['jonathan', 'johnathan', 'jonathon', 'johnathon'],
  ['philip', 'phillip', 'filip'],
  ['peter', 'petr', 'pyotr', 'pieter'],
  ['rachel', 'rachael', 'racheal'],
  ['sean', 'shaun', 'shawn'],
  ['teresa', 'theresa', 'terresa'],
  ['tracy', 'tracey'],
  ['vivian', 'vivien', 'vivianne'],
  ['isabel', 'isabelle', 'isobel', 'ysabel'],
  ['madeline', 'madeleine', 'madelyn'],
  ['marc', 'mark'],
  ['michele', 'michelle'],
  ['nicholas', 'nicolas', 'nikolas'],
  ['reginald', 'reginauld'],
  ['sydney', 'sidney'],
  ['zachary', 'zachery', 'zackary'],
  ['alan', 'allan', 'allen'],
  ['bernard', 'barnard'],
  ['bridget', 'bridgette', 'brigitte'],
  ['caitlin', 'katelyn', 'kaitlyn', 'caitlyn'],
  ['carolyn', 'caroline', 'carolina'],
  ['cindy', 'cyndi'],
  ['clifford', 'clifton'],
  ['elisabeth', 'elizabeth', 'elisabet'],
  ['ellen', 'elen', 'helen', 'helene'],
  ['esther', 'ester'],
  ['gerald', 'jerald', 'gerrald'],
  ['gwendolyn', 'gwendoline'],
  ['hayley', 'haley', 'hailey'],
  ['jaclyn', 'jacquelyn', 'jacqueline'],
  ['jasmine', 'jasmin', 'yasmin', 'yasmine'],
  ['kristen', 'kristin', 'christen'],
  ['kristopher', 'christopher', 'kristofer'],
  ['lindsay', 'lindsey'],
  ['lucille', 'lucile'],
  ['marilyn', 'marylyn', 'marylin'],
  ['maureen', 'moreen'],
  ['meredith', 'merideth'],
  ['nathaniel', 'nathanael', 'nathanial'],
  ['neil', 'neal', 'niel'],
  ['rebecca', 'rebekah', 'rebeca'],
  ['rodney', 'rodnee'],
  ['sherry', 'sheri', 'sherri', 'cheri'],
  ['stacy', 'stacey'],
  ['terry', 'terri', 'teri'],
  ['tiffany', 'tiffani'],
  ['whitney', 'witney'],
  ['aisha', 'ayesha', 'aisha', 'ayisha', 'aysha'],
  ['fatima', 'fatimah', 'fathima', 'fatema'],
  ['maryam', 'mariam', 'meryem', 'mariyam'],
  ['zainab', 'zaynab', 'zeinab'],
  ['khadija', 'khadeeja', 'khadijah'],
  ['smith', 'smyth', 'smythe'],
  ['stewart', 'stuart'],
  ['clark', 'clarke'],
  ['brown', 'browne'],
  ['bergman', 'bergmann'],
  ['moore', 'moor'],
  ['thompson', 'thomson', 'tompson'],
  ['anderson', 'andersen'],
  ['pedersen', 'pederson', 'petersen', 'peterson'],
  ['johnson', 'johnsen'],
  ['macdonald', 'mcdonald'],
  ['mackenzie', 'mckenzie'],
  ['macintosh', 'mcintosh'],
  ['macarthur', 'mcarthur'],
  ['oconnor', 'o connor', 'oconner'],
  ['reilly', 'riley', 'reily'],
  ['schmidt', 'schmitt', 'schmit'],
  ['meyer', 'meier', 'mayer', 'maier'],
  ['schneider', 'snyder', 'snider'],
  ['weber', 'webber'],
  ['muller', 'mueller', 'moeller'],
  ['bauer', 'baur'],
  ['fischer', 'fisher'],
  ['wagner', 'waggoner'],
  ['gonzalez', 'gonzalès', 'gonzales'],
  ['rodriguez', 'rodrigues'],
  ['hernandez', 'hernandes'],
  ['fernandez', 'fernandes'],
  ['gomez', 'gomes'],
  ['perez', 'peres'],
  ['sanchez', 'sanches'],
  ['ramirez', 'ramires'],
  ['martinez', 'martines'],
  ['lopez', 'lopes'],
  ['alvarez', 'alvares'],
  ['nunez', 'nunes'],
  ['chowdhury', 'chaudhary', 'choudhury', 'chaudhry', 'chowdhary', 'choudhary'],
  ['banerjee', 'bandyopadhyay', 'banerji'],
  ['mukherjee', 'mukhopadhyay', 'mukherji'],
  ['chatterjee', 'chattopadhyay', 'chatterji'],
  ['agarwal', 'aggarwal', 'agrawal', 'agarwala'],
  ['srivastava', 'shrivastava', 'srivastav'],
  ['sinha', 'sinhaa'],
  ['gupta', 'guptaa'],
  ['reddy', 'reddi'],
  ['naidu', 'naidoo'],
  ['iyer', 'ayyar'],
  ['iyengar', 'ayyangar'],
  ['pillai', 'pillay'],
  ['nair', 'nayar'],
  ['menon', 'menen'],
  ['deshpande', 'deshpandey'],
  ['kulkarni', 'kulkarny'],
  ['bhattacharya', 'bhattacharjee', 'bhattacharyya'],
];

/** Same source name, different romanisation. */
const TRANSLITERATION_VARIANTS: string[][] = [
  ['mohammad', 'muhammad', 'mohammed', 'muhammed', 'mohamad', 'mohamed', 'muhamad', 'mahomed'],
  ['ahmad', 'ahmed', 'ahmet'],
  ['mahmoud', 'mahmud', 'mahmood', 'mehmood'],
  ['abdul', 'abdel', 'abd', 'abdool'],
  ['abdullah', 'abdallah', 'abdulla', 'abdollah'],
  ['abdulrahman', 'abdurrahman', 'abdelrahman', 'abdurahman'],
  ['rahman', 'rehman', 'rahmaan'],
  ['hassan', 'hasan', 'hassaan'],
  ['hussain', 'hussein', 'husain', 'hosein', 'hussayn'],
  ['ali', 'aly', 'alee'],
  ['omar', 'umar', 'omer'],
  ['usman', 'uthman', 'osman', 'othman'],
  ['ibrahim', 'ebrahim', 'brahim'],
  ['yusuf', 'yousuf', 'yousef', 'youssef', 'yusef', 'joseph'],
  ['ismail', 'ismael', 'esmail'],
  ['khalid', 'khaled'],
  ['saeed', 'said', 'sayed', 'sayeed', 'saiyed'],
  ['sulaiman', 'suleiman', 'sulayman', 'soliman'],
  ['tariq', 'tarek', 'tarik'],
  ['jamal', 'gamal'],
  ['nasser', 'nasir', 'naser', 'nassir'],
  ['karim', 'kareem'],
  ['salim', 'saleem', 'selim'],
  ['rashid', 'rasheed'],
  ['hamza', 'hamzah'],
  ['bilal', 'belal'],
  ['faisal', 'faysal', 'feisal'],
  ['zakaria', 'zakariya', 'zachariah'],
  ['noor', 'nour', 'nur', 'noora'],
  ['yahya', 'yehia', 'yahia'],
  ['siddiqui', 'siddiqi', 'sadiqui'],
  ['sheikh', 'shaikh', 'shaykh', 'shekh'],
  ['syed', 'sayyid', 'sayed', 'sayyed'],
  ['uddin', 'ud din', 'udeen', 'uddeen'],
  ['iqbal', 'ikbal'],
  ['aslam', 'asalam'],
  ['raza', 'reza', 'rida'],
  ['rahul', 'raahul'],
  ['sharma', 'sarma', 'sharmaa'],
  ['deepak', 'dipak'],
  ['sandeep', 'sundeep'],
  ['pradeep', 'pradip'],
  ['sanjay', 'sanjai'],
  ['vijay', 'bijay', 'vijai'],
  ['ramesh', 'rameshh'],
  ['suresh', 'sureshh'],
  ['krishna', 'krishnan', 'kishan'],
  ['lakshmi', 'laxmi', 'lakshmy'],
  ['saraswati', 'saraswathi'],
  ['ganesh', 'ganesha', 'ganeshan'],
  ['pooja', 'puja'],
  ['neha', 'nehaa'],
  ['shweta', 'sweta', 'shwetha'],
  ['geeta', 'gita', 'geetha'],
  ['seema', 'sima'],
  ['meena', 'mina', 'meenaa'],
  ['aleksandr', 'alexander', 'aleksander', 'alexandr'],
  ['dmitry', 'dmitri', 'dmitriy'],
  ['sergey', 'sergei', 'serguei'],
  ['yuri', 'yury', 'iurii'],
  ['nikolay', 'nikolai', 'nicolai'],
  ['mikhail', 'michail'],
  ['andrey', 'andrei'],
  ['evgeny', 'evgeni', 'yevgeny'],
  ['ekaterina', 'yekaterina'],
  ['tatiana', 'tatyana'],
  ['natalia', 'natalya', 'nataliya'],
  ['ioannis', 'yiannis', 'giannis'],
  ['georgios', 'yorgos', 'giorgos'],
  ['dimitrios', 'dimitris'],
];

/**
 * East Asian romanisation families. Deliberately weak: `Chen` and `Tan` are the
 * same Han surname in different dialects, but in a Latin-script registry they
 * far more often belong to two different people.
 */
const ROMANIZATION_FAMILIES: string[][] = [
  ['zhang', 'chang', 'cheung'],
  ['wang', 'wong'],
  ['chen', 'chan', 'tan'],
  ['li', 'lee', 'ly'],
  ['liu', 'lau', 'lew'],
  ['huang', 'hwang'],
  ['zhou', 'chou', 'chow'],
  ['xu', 'hsu'],
  ['zhao', 'chao'],
  ['kim', 'gim'],
  ['park', 'pak', 'bak'],
  ['choi', 'choe'],
  ['jeong', 'jung', 'chung'],
  ['nguyen', 'nguyn'],
  ['tran', 'chan'],
];

/** Diminutives and short forms. */
export const NICKNAMES: string[][] = [
  ['robert', 'bob', 'bobby', 'rob', 'robbie', 'bert'],
  ['william', 'bill', 'billy', 'will', 'willie', 'liam', 'wm'],
  ['richard', 'rick', 'ricky', 'dick', 'rich', 'richie'],
  ['michael', 'mike', 'mikey', 'mick', 'mickey'],
  ['james', 'jim', 'jimmy', 'jamie', 'jas'],
  ['john', 'jack', 'johnny', 'jonny'],
  ['charles', 'charlie', 'chuck', 'chas', 'charly'],
  ['thomas', 'tom', 'tommy', 'thos'],
  ['joseph', 'joe', 'joey', 'jos'],
  ['christopher', 'chris', 'kit', 'topher'],
  ['daniel', 'dan', 'danny', 'danl'],
  ['matthew', 'matt', 'matty'],
  ['anthony', 'tony', 'ant'],
  ['edward', 'ed', 'eddie', 'ted', 'teddy', 'ned', 'edwd'],
  ['david', 'dave', 'davey'],
  ['andrew', 'andy', 'drew'],
  ['benjamin', 'ben', 'benny', 'benj'],
  ['samuel', 'sam', 'sammy', 'saml'],
  ['alexander', 'alex', 'alec', 'sasha', 'sandy', 'xander', 'alexr'],
  ['nicholas', 'nick', 'nicky', 'cole'],
  ['patrick', 'pat', 'paddy', 'rick'],
  ['timothy', 'tim', 'timmy'],
  ['kenneth', 'ken', 'kenny'],
  ['ronald', 'ron', 'ronnie'],
  ['donald', 'don', 'donnie'],
  ['gregory', 'greg', 'gregg'],
  ['jeffrey', 'jeff'],
  ['lawrence', 'larry', 'laurie', 'lance'],
  ['leonard', 'leo', 'len', 'lenny'],
  ['raymond', 'ray'],
  ['eugene', 'gene'],
  ['albert', 'al', 'albie', 'bert'],
  ['arthur', 'art', 'artie'],
  ['frederick', 'fred', 'freddie', 'fritz'],
  ['harold', 'harry', 'hal'],
  ['henry', 'hank', 'harry', 'hal'],
  ['walter', 'walt', 'wally'],
  ['george', 'georgie', 'geo'],
  ['peter', 'pete', 'petey'],
  ['philip', 'phil'],
  ['russell', 'russ', 'rusty'],
  ['stanley', 'stan'],
  ['stephen', 'steve', 'stevie'],
  ['terence', 'terry'],
  ['vincent', 'vince', 'vinny'],
  ['zachary', 'zach', 'zack'],
  ['abraham', 'abe', 'bram'],
  ['bernard', 'bernie', 'barney'],
  ['calvin', 'cal'],
  ['clifford', 'cliff'],
  ['douglas', 'doug'],
  ['francis', 'frank', 'frankie'],
  ['gerald', 'gerry', 'jerry'],
  ['herbert', 'herb', 'bert'],
  ['howard', 'howie'],
  ['isaac', 'ike'],
  ['jacob', 'jake', 'jack'],
  ['jonathan', 'jon', 'jonny'],
  ['joshua', 'josh'],
  ['martin', 'marty'],
  ['maurice', 'morrie'],
  ['nathaniel', 'nate', 'nat'],
  ['norman', 'norm'],
  ['oliver', 'ollie'],
  ['randolph', 'randy', 'rand'],
  ['reginald', 'reggie', 'reg'],
  ['rodney', 'rod'],
  ['roger', 'rodge'],
  ['solomon', 'sol'],
  ['theodore', 'ted', 'teddy', 'theo'],
  ['victor', 'vic'],
  ['warren', 'ren'],
  ['wesley', 'wes'],
  ['wilfred', 'wilf'],
  ['abigail', 'abby', 'gail'],
  ['alexandra', 'alex', 'sasha', 'sandra', 'lexi'],
  ['amanda', 'mandy'],
  ['angela', 'angie'],
  ['barbara', 'barb', 'babs'],
  ['beatrice', 'bea'],
  ['bernadette', 'bernie'],
  ['bridget', 'bridie'],
  ['catherine', 'cathy', 'kate', 'katie', 'kitty', 'cate', 'kath'],
  ['charlotte', 'lottie', 'charlie'],
  ['christina', 'chris', 'tina', 'christy'],
  ['christine', 'chris', 'chrissy', 'tina'],
  ['cynthia', 'cindy'],
  ['deborah', 'debbie', 'deb'],
  ['dorothy', 'dot', 'dottie', 'dolly'],
  ['eleanor', 'ellie', 'nell', 'nora'],
  ['elizabeth', 'liz', 'beth', 'betty', 'eliza', 'lizzie', 'betsy', 'libby', 'eliz'],
  ['emily', 'em', 'emmy'],
  ['florence', 'flo', 'flossie'],
  ['frances', 'fran', 'francie'],
  ['gabrielle', 'gaby', 'gabby'],
  ['genevieve', 'gen'],
  ['gertrude', 'gertie', 'trudy'],
  ['gwendolyn', 'gwen'],
  ['harriet', 'hattie'],
  ['jacqueline', 'jackie', 'jacqui'],
  ['jennifer', 'jen', 'jenny'],
  ['jessica', 'jess', 'jessie'],
  ['josephine', 'jo', 'josie'],
  ['judith', 'judy', 'jude'],
  ['katherine', 'kathy', 'kate', 'katie', 'kay'],
  ['linda', 'lindy'],
  ['margaret', 'maggie', 'peggy', 'meg', 'marge', 'greta', 'marg'],
  ['martha', 'marty', 'mattie'],
  ['mary', 'molly', 'mae', 'may', 'mamie'],
  ['matilda', 'tilly', 'mattie'],
  ['melissa', 'mel', 'missy'],
  ['michelle', 'shelly', 'micky'],
  ['nancy', 'nan'],
  ['pamela', 'pam'],
  ['patricia', 'pat', 'patty', 'trish', 'tricia'],
  ['penelope', 'penny'],
  ['priscilla', 'cilla'],
  ['rebecca', 'becky', 'becca'],
  ['rosemary', 'rosie', 'rose'],
  ['samantha', 'sam', 'sammy'],
  ['sandra', 'sandy'],
  ['sharon', 'shari'],
  ['stephanie', 'steph', 'stevie'],
  ['susan', 'sue', 'susie', 'suzy'],
  ['sylvia', 'sylvie'],
  ['theresa', 'terry', 'tess', 'tracy'],
  ['valerie', 'val'],
  ['veronica', 'ronnie', 'vera'],
  ['victoria', 'vicky', 'tori', 'vicki'],
  ['virginia', 'ginny', 'ginger'],
  ['wilhelmina', 'mina', 'billie'],
  ['yvonne', 'vonnie'],
  ['mohammad', 'mohd', 'muhd', 'md', 'mohd.', 'mo'],
  ['abdul', 'abd'],
  ['krishnamurthy', 'krishna'],
  ['venkatesh', 'venkat'],
  ['rajendra', 'raju'],
  ['ramachandran', 'ram'],
  ['subramanian', 'subbu'],
];

/**
 * Traditional English hypocorisms.
 *
 * Kept separate from the general nickname table because English is this
 * package's primary target and the list needs to be maintained as a unit. Most
 * of these are *not* derivable from the full name by any rule — `Peggy` from
 * `Margaret`, `Polly` from `Mary`, `Nancy` from `Ann` — which is exactly why a
 * dictionary is the only thing that recovers them.
 */
export const ENGLISH_NICKNAMES: string[][] = [
  // Feminine
  ['margaret', 'peggy', 'peg', 'madge', 'daisy', 'greta', 'meg', 'maggie', 'marge'],
  ['mary', 'polly', 'mollie', 'mamie', 'minnie'],
  ['sarah', 'sally', 'sadie', 'sallie'],
  ['ann', 'nancy', 'nan', 'nanny', 'annie'],
  ['anne', 'nancy', 'nan', 'annie'],
  ['agnes', 'nancy', 'aggie', 'nessa'],
  ['dorothy', 'dot', 'dottie', 'dolly', 'doll'],
  ['mildred', 'millie', 'milly'],
  ['millicent', 'millie', 'milly'],
  ['winifred', 'winnie', 'freda'],
  ['matilda', 'tillie', 'mattie', 'patty'],
  ['cecilia', 'cissy', 'cece', 'celia'],
  ['cecily', 'cissy', 'cece'],
  ['euphemia', 'effie'],
  ['frances', 'fanny', 'fran', 'francie', 'frankie'],
  ['charlotte', 'lottie', 'chattie'],
  ['lavinia', 'vinnie'],
  ['eleanor', 'nell', 'nellie', 'nora', 'ellie'],
  ['honora', 'nora', 'norah', 'honor'],
  ['helen', 'nell', 'nellie', 'lena'],
  ['henrietta', 'etta', 'hettie', 'netta', 'harriet'],
  ['harriet', 'hattie', 'hetty'],
  ['constance', 'connie'],
  ['edith', 'edie'],
  ['esther', 'essie', 'hester'],
  ['florence', 'flo', 'flossie', 'floy'],
  ['georgina', 'georgie', 'gina'],
  ['gertrude', 'gertie', 'trudy'],
  ['isabella', 'bella', 'belle', 'izzy'],
  ['janet', 'jan', 'nettie'],
  ['jane', 'janie', 'jenny'],
  ['joanna', 'joanie', 'jo'],
  ['judith', 'judy', 'jude'],
  ['lillian', 'lily', 'lil', 'lillie'],
  ['lucinda', 'lucy', 'cindy'],
  ['marjorie', 'madge', 'marge', 'margie'],
  ['martha', 'mattie', 'patty', 'marty'],
  ['melissa', 'missy', 'lissa'],
  ['olivia', 'livvy', 'liv'],
  ['patience', 'patty'],
  ['penelope', 'penny'],
  ['philippa', 'pippa'],
  ['priscilla', 'prissy', 'cilla'],
  ['prudence', 'prue'],
  ['rachel', 'rae', 'shelly'],
  ['rebecca', 'reba', 'becca', 'becky'],
  ['roberta', 'bobbie', 'birdie'],
  ['rosalind', 'roz', 'rosie'],
  ['susannah', 'susie', 'sukey', 'sue'],
  ['theresa', 'tessa', 'tess'],
  ['veronica', 'ronnie', 'vera'],
  ['victoria', 'vita', 'tori', 'vicky'],
  ['virginia', 'ginny', 'ginger'],
  ['amelia', 'millie', 'amy'],
  ['beatrice', 'bea', 'trixie'],
  ['caroline', 'carrie', 'caddie'],
  ['emily', 'emmy', 'millie'],
  ['delilah', 'lila'],

  // Masculine
  ['henry', 'hank', 'hal', 'harry'],
  ['harold', 'harry', 'hal'],
  ['charles', 'chuck', 'charlie', 'chas'],
  ['edward', 'ned', 'ted', 'teddy', 'eddie', 'ed'],
  ['augustus', 'gus', 'augie'],
  ['august', 'gus', 'augie'],
  ['ezekiel', 'zeke'],
  ['abraham', 'bram', 'abe'],
  ['nathaniel', 'nate', 'nat'],
  ['nathan', 'nate', 'nat'],
  ['oliver', 'ollie', 'noll'],
  ['percival', 'percy'],
  ['ralph', 'rafe'],
  ['solomon', 'sol'],
  ['vernon', 'vern'],
  ['walter', 'wally', 'walt'],
  ['montgomery', 'monty'],
  ['bartholomew', 'bart'],
  ['cornelius', 'con', 'neil'],
  ['gilbert', 'gil'],
  ['alonzo', 'lon'],
  ['milton', 'milt'],
  ['calvin', 'cal'],
  ['cyrus', 'cy'],
  ['reuben', 'rube'],
  ['silas', 'si'],
  ['sylvester', 'vester'],
  ['wilbur', 'will'],
  ['wilfred', 'wilf'],
  ['archibald', 'archie'],
  ['duncan', 'dunk'],
  ['ernest', 'ernie'],
  ['everett', 'rett'],
  ['gordon', 'gordy'],
  ['malcolm', 'mal'],
  ['jeremiah', 'jere', 'jerry'],
  ['jeremy', 'jem', 'jerry'],
  ['roderick', 'rod', 'rory'],
  ['barnabas', 'barney'],
  ['obadiah', 'obie'],
  ['horace', 'horry'],
  ['clarence', 'clare'],
  ['leopold', 'leo'],
  ['lionel', 'leo'],
  ['mortimer', 'mort'],
  ['jerome', 'jerry'],
];

/** Cross-language cognates. Weak evidence, disabled in strict mode. */
const TRANSLATIONS: string[][] = [
  ['john', 'juan', 'jean', 'johann', 'johannes', 'giovanni', 'ivan', 'jan', 'joao', 'yohannes'],
  ['james', 'jaime', 'jacques', 'giacomo', 'jakob', 'diego'],
  ['peter', 'pedro', 'pierre', 'pietro', 'piotr'],
  ['joseph', 'jose', 'giuseppe', 'josef', 'yusuf'],
  ['michael', 'miguel', 'michel', 'michele', 'mikhail', 'michal'],
  ['george', 'jorge', 'georges', 'giorgio', 'georgios', 'jerzy'],
  ['charles', 'carlos', 'carlo', 'karel'],
  ['anthony', 'antonio', 'antoine', 'anton'],
  ['paul', 'pablo', 'paolo', 'pavel'],
  ['stephen', 'esteban', 'etienne', 'stefano', 'istvan'],
  ['mary', 'maria', 'marie', 'mariya'],
  ['catherine', 'catalina', 'caterina', 'ekaterina'],
  ['elizabeth', 'isabel', 'elisabetta', 'elzbieta'],
  ['margaret', 'margarita', 'marguerite', 'margarethe'],
  ['helen', 'elena', 'helene', 'eleni'],
  ['andrew', 'andres', 'andre', 'andrea', 'andrzej'],
  ['francis', 'francisco', 'francois', 'francesco'],
  ['louis', 'luis', 'luigi', 'ludwig'],
  ['nicholas', 'nicolas', 'niccolo', 'mikolaj'],
  ['thomas', 'tomas', 'tommaso', 'tomasz'],
];

function build(groups: string[][], kind: AliasGroup['kind'], strength: number): AliasGroup[] {
  return groups.map((members) => ({
    id: `${kind}:${members[0]}`,
    members: [...new Set(members)],
    kind,
    strength,
  }));
}

export const DEFAULT_ALIAS_GROUPS: readonly AliasGroup[] = Object.freeze([
  ...build(SPELLING_VARIANTS, 'variant', 0.97),
  ...build(TRANSLITERATION_VARIANTS, 'transliteration', 0.96),
  ...build(NICKNAMES, 'nickname', 0.9),
  ...build(ENGLISH_NICKNAMES, 'nickname', 0.9),
  ...build(ROMANIZATION_FAMILIES, 'transliteration', 0.62),
  ...build(TRANSLATIONS, 'translation', 0.55),
]);

/**
 * Contraction abbreviations that skip internal letters. Recognised explicitly
 * because a subsequence test alone is too permissive.
 */
export const KNOWN_CONTRACTIONS: Record<string, string[]> = {
  mohd: ['mohammad', 'muhammad', 'mohammed'],
  muhd: ['mohammad', 'muhammad', 'mohammed'],
  mhd: ['mohammad', 'muhammad', 'mohammed'],
  md: ['mohammad', 'muhammad', 'mohammed'],
  wm: ['william'],
  robt: ['robert'],
  richd: ['richard'],
  jno: ['john'],
  jas: ['james'],
  jos: ['joseph'],
  geo: ['george'],
  thos: ['thomas'],
  chas: ['charles'],
  benj: ['benjamin'],
  danl: ['daniel'],
  edwd: ['edward'],
  saml: ['samuel'],
  alexr: ['alexander'],
  eliz: ['elizabeth'],
  marg: ['margaret'],
  kath: ['katherine', 'catherine'],
  xtopher: ['christopher'],
  xpher: ['christopher'],
};

/**
 * Given names that are frequent enough as standalone names that treating them
 * as a truncation of a longer name would create false positives.
 * `Raj` is not evidence for `Rajesh`.
 */
export const STANDALONE_SHORT_NAMES: ReadonlySet<string> = new Set([
  'raj',
  'ram',
  'ravi',
  'ali',
  'ana',
  'anna',
  'jan',
  'sam',
  'max',
  'ben',
  'dan',
  'don',
  'ron',
  'tom',
  'tim',
  'jim',
  'joe',
  'ken',
  'leo',
  'lee',
  'roy',
  'ray',
  'rex',
  'guy',
  'ian',
  'eve',
  'amy',
  'joy',
  'kim',
  'kai',
  'ali',
  'omar',
  'noor',
  'rani',
  'devi',
  'mina',
  'gita',
  'asha',
  'usha',
  'lata',
  'nina',
  'rita',
  'sita',
  'maya',
  'mark',
  'marc',
  'paul',
  'carl',
  'karl',
  'erik',
  'eric',
  'alan',
  'adam',
  'noah',
  'liam',
  'luca',
  'hugo',
  'juan',
  'jose',
  'luis',
  'ivan',
  'igor',
  'oleg',
  'boris',
  'pablo',
  'diego',
  'chen',
  'wang',
  'li',
  'lin',
  'kim',
  'park',
  'han',
  'jin',
  'yan',
  'ann',
  'anne',
  'jane',
  'john',
  'jon',
  'ted',
  'bob',
  'rob',
  'bill',
  'will',
  'nick',
  'rick',
  'mike',
  'dave',
  'greg',
  'jeff',
  'todd',
  'chad',
  'kyle',
  'sean',
  'ryan',
  'dean',
  'glen',
  'neil',
  'earl',
  'gary',
  'jerry',
  'larry',
  'barry',
  'harry',
  'terry',
  'perry',
  'kerry',
  'amit',
  'ajay',
  'arun',
  'anil',
  'atul',
  'ashok',
  'vinod',
  'vijay',
  'sunil',
]);

/**
 * Curated look-alike pairs that are close in string space yet reliably denote
 * different people. Each entry lowers the score rather than vetoing the match.
 */
export const DISTINCT_NAME_PAIRS: ReadonlyArray<readonly [string, string]> = Object.freeze([
  ['michael', 'michelle'],
  ['daniel', 'danielle'],
  ['gabriel', 'gabrielle'],
  ['joel', 'joell'],
  ['jean', 'joan'],
  ['jon', 'jan'],
  ['john', 'joan'],
  ['john', 'jean'],
  ['paul', 'paula'],
  ['patrick', 'patricia'],
  ['stephen', 'stephanie'],
  ['nicholas', 'nicole'],
  ['nicolas', 'nicole'],
  ['christian', 'christina'],
  ['christopher', 'christina'],
  ['martin', 'martina'],
  ['julian', 'julia'],
  ['adrian', 'adriana'],
  ['fabian', 'fabiana'],
  ['simon', 'simone'],
  ['rene', 'irene'],
  ['carl', 'carla'],
  ['eric', 'erica'],
  ['frank', 'franca'],
  ['louis', 'louise'],
  ['francis', 'frances'],
  ['dominic', 'dominique'],
  ['ali', 'alia'],
  ['amin', 'amina'],
  ['karim', 'karima'],
  ['nadir', 'nadira'],
  ['samir', 'samira'],
  ['yasir', 'yasira'],
  ['raj', 'rajesh'],
  ['raj', 'rajiv'],
  ['raj', 'rajan'],
  ['ram', 'ramesh'],
  ['ram', 'raman'],
  ['ravi', 'ravindra'],
  ['sur', 'suresh'],
  ['dev', 'devesh'],
  ['man', 'manoj'],
  ['sun', 'sunil'],
  ['ana', 'anastasia'],
  ['ana', 'anahita'],
  ['lee', 'leigh'],
  ['chan', 'chang'],
  ['chen', 'cheng'],
  ['kim', 'kimberly'],
  ['han', 'hank'],
  ['jan', 'jane'],
  ['dean', 'deana'],
  ['brian', 'briana'],
  ['justin', 'justine'],
  ['jose', 'josef'],
  ['maria', 'mario'],
  ['andrea', 'andrew'],
  ['alexander', 'alexandra'],
  ['alexander', 'alexandre'],
  ['alex', 'alexa'],
  ['gene', 'jean'],
  ['neil', 'nell'],
  ['sara', 'sana'],
  ['tara', 'tania'],
  ['nora', 'dora'],
  ['mark', 'marks'],
  ['smith', 'smit'],
  ['jones', 'jonas'],
  ['wright', 'white'],
  ['harris', 'harrison'],
  ['robert', 'roberts'],
  ['richard', 'richards'],
  ['william', 'williams'],
  ['peter', 'peters'],
  ['stephen', 'stephens'],
  ['edward', 'edwards'],
  ['thomas', 'thompson'],
  ['johnson', 'johnston'],
  ['jackson', 'jaxon'],
  ['nelson', 'neilson'],
  ['wilson', 'willson'],
  ['marco', 'mario'],
  ['sanjay', 'sanjiv'],
  ['amit', 'ankit'],
  ['aditya', 'aditi'],
  ['hassan', 'hussain'],
  ['hasan', 'husain'],
  ['zhang', 'chang'],
  ['baker', 'walker'],
  ['petrov', 'popov'],
  ['john', 'johns'],
  ['david', 'davids'],
  ['daniel', 'daniels'],
  ['brook', 'brooks'],
  ['wood', 'woods'],
  ['field', 'fields'],
  ['well', 'wells'],
  ['hill', 'hills'],
  ['river', 'rivers'],
  ['bank', 'banks'],
  ['andrew', 'andrews'],
  ['evan', 'evans'],
  ['owen', 'owens'],
  ['jenkin', 'jenkins'],
  ['watkin', 'watkins'],
  ['perkin', 'perkins'],
  ['collin', 'collins'],
]);
